### ISSUE TITLE
改善采纳/试用流程

### ISSUE THREAD

**Issue by timfeirg** [timfeirg/lain-cli#38]
由于需要增添集群配置, 重新打包做内部发版, lain 一直无法轻易的试用. 不过并不需要这样, 还是可以做不少事情来优化的:

- [x] 将上游 lain 发布到 pypi: https://pypi.org/project/lain
- [ ] 丰富文档和 readme, 教大家如何从 pypi 安装 lain, 然后增加集群配置
- [ ] 将 install from pypi.org 作为一个合法合理的用法进行评估, 让没条件自行发版的个人也能用上 lain

**Comment by hongqn** [comment]
建议：

把 lain_cli/cluster_values 做成 plugin 机制，lain 在运行时自己发现安装了的 cluster 。

例如，某个叫做 xyz 的组织，如果想使用 lain ，可以这样安装：

```sh
pip install lain  # from pypi.org
pip install xzy-lain-clusters -i https://pypi.xyz.com
```

这样即可以集中化管理集群配置，又可以直接安装 lain 使用。

配合上允许本地配置 cluster 集群（例如 ~/.config/lain/my-cluster.yaml) ，个人也可以较容易的使用 lain 。

额外可以考虑的，是增加配置文件的版本机制，这样当 lain 发布了不兼容改动时，可以通过配置文件的版本号来判断是否需要提醒用户修改集群配置。

**Comment by timfeirg** [comment]
如果做了代码-配置分离, 势必要求更新代码和更新配置区别对待. 而目前所有使用 lain 的团队, 事实上又都在定制 lain 的代码, 已经在自行管理内部分支发版. 对于这些团队来说, 代码-配置分离模式没有额外的好处了, 因为本来就不会直接安装上游 lain.

这个 issue 的目的也仅仅是为了让想尝试 lain 的人更容易进行评估, 达到这个目的就好, 不会对使用模式做拓展.

**Comment by timfeirg** [comment]
readme 里加入了简略的相关文档.
